//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestaoP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alocacao_Professor_Turma
    {
        public int AlocacaoProfessorTurma_id { get; set; }
        public Nullable<int> displinaProfessorFK { get; set; }
        public Nullable<int> classeTurmaFK { get; set; }
        public Nullable<int> anoLectivo { get; set; }
    
        public virtual Classe_Turma Classe_Turma { get; set; }
        public virtual Disciplina_Professor Disciplina_Professor { get; set; }
    }
}
