//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestaoP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alocacao_Aluno_Professor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alocacao_Aluno_Professor()
        {
            this.Avaliacaos = new HashSet<Avaliacao>();
        }
    
        public int Alocacao_Aluno_Professor_id { get; set; }
        public Nullable<int> alunoFK { get; set; }
        public Nullable<int> disciplinaProfessorFK { get; set; }
        public Nullable<int> classeTurmaFK { get; set; }
        public Nullable<int> anoLectivo { get; set; }
    
        public virtual Aluno Aluno { get; set; }
        public virtual Classe_Turma Classe_Turma { get; set; }
        public virtual Disciplina_Professor Disciplina_Professor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Avaliacao> Avaliacaos { get; set; }
    }
}
