//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestaoP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avaliacao
    {
        public int Avaliacao_id { get; set; }
        public Nullable<int> tipoAvaliacaoFK { get; set; }
        public Nullable<int> trimestreFK { get; set; }
        public Nullable<int> alocacaoAlunoProfessorFK { get; set; }
        public Nullable<float> nota { get; set; }
    
        public virtual Alocacao_Aluno_Professor Alocacao_Aluno_Professor { get; set; }
        public virtual Tipo_Avaliacao Tipo_Avaliacao { get; set; }
        public virtual Trimestre Trimestre { get; set; }
    }
}
