//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestaoP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classe_Turma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Classe_Turma()
        {
            this.Alocacao_Aluno_Professor = new HashSet<Alocacao_Aluno_Professor>();
            this.Alocacao_Aluno_Turma = new HashSet<Alocacao_Aluno_Turma>();
            this.Alocacao_Professor_Turma = new HashSet<Alocacao_Professor_Turma>();
        }
    
        public int ClasseTurma_id { get; set; }
        public Nullable<int> classeFK { get; set; }
        public Nullable<int> turmaFK { get; set; }
        public Nullable<int> turnoFK { get; set; }
        public Nullable<int> seccaoFK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alocacao_Aluno_Professor> Alocacao_Aluno_Professor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alocacao_Aluno_Turma> Alocacao_Aluno_Turma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alocacao_Professor_Turma> Alocacao_Professor_Turma { get; set; }
        public virtual Classe Classe { get; set; }
        public virtual Seccao Seccao { get; set; }
        public virtual Turma Turma { get; set; }
        public virtual Turno Turno { get; set; }
    }
}
