//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestaoP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SGPEntities : DbContext
    {
        public SGPEntities()
            : base("name=SGPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alocacao_Aluno_Professor> Alocacao_Aluno_Professor { get; set; }
        public virtual DbSet<Alocacao_Aluno_Turma> Alocacao_Aluno_Turma { get; set; }
        public virtual DbSet<Alocacao_Professor_Turma> Alocacao_Professor_Turma { get; set; }
        public virtual DbSet<Aluno> Alunoes { get; set; }
        public virtual DbSet<Avaliacao> Avaliacaos { get; set; }
        public virtual DbSet<Classe> Classes { get; set; }
        public virtual DbSet<Classe_Turma> Classe_Turma { get; set; }
        public virtual DbSet<Disciplina> Disciplinas { get; set; }
        public virtual DbSet<Disciplina_Professor> Disciplina_Professor { get; set; }
        public virtual DbSet<Endereco> Enderecoes { get; set; }
        public virtual DbSet<Genero> Generoes { get; set; }
        public virtual DbSet<Papel> Papels { get; set; }
        public virtual DbSet<Professor> Professors { get; set; }
        public virtual DbSet<Seccao> Seccaos { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tipo_Avaliacao> Tipo_Avaliacao { get; set; }
        public virtual DbSet<Trimestre> Trimestres { get; set; }
        public virtual DbSet<Turma> Turmas { get; set; }
        public virtual DbSet<Turno> Turnoes { get; set; }
        public virtual DbSet<Utilizador> Utilizadors { get; set; }
    }
}
