//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestaoP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilizador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilizador()
        {
            this.Alunoes = new HashSet<Aluno>();
            this.Professors = new HashSet<Professor>();
        }
    
        public int Utilizador_id { get; set; }
        public string nome { get; set; }
        public string palavra_passe { get; set; }
        public string nomeUtilizador { get; set; }
        public Nullable<int> enderecoFK { get; set; }
        public Nullable<int> generoFK { get; set; }
        public Nullable<int> celular { get; set; }
        public Nullable<int> papelFK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aluno> Alunoes { get; set; }
        public virtual Endereco Endereco { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual Papel Papel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Professor> Professors { get; set; }
    }
}
